### ISSUE TITLE
🧪SPIKE DNS Testing 

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#376]
**User Story:** 
As a DevOps engineer I want to ensure that our infrastructure has got the capacity to deal with increased traffic flow so that we can continue to provide value to our end users.

**Context:** 
There is a business wide push to enable PDNS across the estate in order to improve security. Our MoJ DNS service provides this but it is not in use across the entire estate. Currently (exact number tbd) some devices are using Infloblox DNS service. The current tactical solution is to point to the MoJ DNS service in order to provide the PDNS service. 

TBD the tests needed in order to ensure our infrastructure can cope with the increased traffic. 

Link to previous tests conducted by the DevOps team https://github.com/ministryofjustice/staff-device-dns-server/blob/main/documentation/performance-benchmarks.md

**Comment by darey-io** [comment]
During this spike, It has been established that dnsperf can be executed from "Corsham Test Bastion" server in AWS. 

Here is an output of a test that was conducted 

`ubuntu@ip-10-180-82-176:~$ time dnsperf -s staff-device-production-dns-754e69ecf996b619.elb.eu-west-2.amazonaws.com         -d test_queryfile         -c 1         -Q 10         -t 2         -l 300
DNS Performance Testing Tool
Nominum Version 2.1.1.0.d

[Status] Command line: dnsperf -s staff-device-production-dns-754e69ecf996b619.elb.eu-west-2.amazonaws.com -d test_queryfile -c 1 -Q 10 -t 2 -l 300
[Status] Sending queries (to 10.180.80.5)
[Status] Started at: Tue Jun 27 13:15:17 2023
[Status] Stopping after 300.000000 seconds
[Status] Testing complete (time limit)

Statistics:

  Queries sent:         3000
  Queries completed:    3000 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 2333 (77.77%), NXDOMAIN 667 (22.23%)
  Average packet size:  request 33, response 117
  Run time (s):         300.000323
  Queries per second:   9.999989

  Average Latency (s):  0.003219 (min 0.000523, max 0.462044)
  Latency StdDev (s):   0.021142


real    5m0.140s
user    0m0.057s
sys     0m0.388s`

Lessons learned

1. Codepipeline did not pick up changes from the code when trying to update the variable to provision a bastion server. This happened because the actual value is supposed to be updated in Parameter store **"/staff-device/dns-dhcp/$ENV/enable_bastion"** and not in the code. 
2. The **generate_tfvars.sh** script in the code base is useful only for development environment. It is not optimized for preprod and prod because all the values override are pulled from parameter store at run time.
3. The Onprem VM is not reachable from the Bastion, hence test was conducted on bastion in AWS. We need to understand more, why it may be necessary to run the tests from the onprem VM
 
Considerations for Implementation
1. The bastion server in AWS is configured as a t2.nano instance type. If the testing will be done here, we will need to configure a larger instance
2. The scope of testing needs to be established. The previous testing that was conducted had 9 tests conducted covering different scenarios. Given the current requirement and load expectations, we will need to be more specific on the desired performance benchmark as this will help us scope the test a lot more better.
 
- Query Load: Desired query load that the DNS server needs to handle. Can we define or articulate what is considered a "heavy load"?
- Concurrency: Desired performance under multiple connections
-  Test Duration: What is the DNS server's stability and performance over an extended period.
-  Response Time:  How quickly do we expect the DNS server to respond. In other words, what is our expectations in terms of DNS server's performance as it relates to latency and responsiveness.
-  Resource Utilization: What is the maximum resource utilization expected under heavy load.
-  Scalability and Load Balancing: Do we care about this? Is this part of what we want to see during the tests?
-  Reporting and Analysis: Do we care about visualizing the test reports for further analysis


With this, we can then proceed with testing.
