### ISSUE TITLE
Implement basic authentication for prometheus endpoint

### ISSUE THREAD

**Issue by jennycasanova** [ministryofjustice/nvvs-devops#429]
Additional ticket brought out following the spike on Grafana metric work carried out in sprint 2nd - 15 August 2023

**Comment by darey-io** [comment]
To protect the https://monitoring-alerting.staff.service.justice.gov.uk/metrics endpoint, we need to create an ingress resource with authentication annotations so that there is a prompt to provide username and password

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /metrics
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.0.3
  name: grafana-metrics
  namespace: grafana
spec:
  ingressClassName: nginx
  rules:
  - host: monitoring-alerting.dev.staff.service.justice.gov.uk
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 80
        path: /metrics
        pathType: Prefix`
