### ISSUE TITLE
Review scaling out metric for DNS cluster

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#432]
**Context:** 

Ahead of the PDNS switch over we need to discuss the current configuration and provision of containers for DNS. We need to decide how many containers are needed and the scaling out configuration for this. 

We need to also assess if we need to add any additional metrics for scaling out.
This ticket is dependent on the DNS testing ticket. 

This ticket has been spun off from ticket [182](url) where we encountered DNS errors. 
We saw a number of unhealthy containers and the service should have auto scaled to prevent issues. Following investigations into the issue the average was being used (this needs to change) and we need to review the scaling out metrics for DNS clusters.

**Comment by tomwells98** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/432?planning-poker) with Zenhub @juddin927 @satishgummadellimoj

**Comment by tomwells98** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops/432?planning-poker) with Zenhub @smjmoj

**Comment by juddin927** [comment]
Reviewed the cluster scaling config which is currently only using CPU metric to scale up, I suggest we also add memory as a scaling up metric too.

**Comment by tomwells98** [comment]
Could be a good introductory ticket for James

**Comment by jamesgreen-moj** [comment]
I think I have discovered a misconfiguration that attributed to the outage on the 15th August 2023. (https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/staff-device-dns-server/182)

Reviewing all the statics I conclude the reason for the outage was due to an increase in traffic between the hours of 12:00-14:00 on the 15 of August.

As a result, many of the ECS tasks got marked as unhealthy causing them to get shutdown. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3IxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--383cb8d41949db569b2313cd90cdb89799044ed5/image.png)

After reading this AWS article: https://repost.aws/knowledge-center/elb-ecs-tasks-improperly-replaced

I believe we need to up the "Health check grace period" (Currently set at 0). This will give the service a grace period, to scale prior to instantly shutting down the containers.

**Comment by jamesgreen-moj** [comment]
UPDATE: Health check grace period is actually only on initiation of the task. "The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started. " --health-check-grace-period-seconds (https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html) 

This means its unlikely this parameter, that attributed to the outage.

**Comment by babatundek** [comment]
This will remain blocked until 444 is completed

**Comment by babatundek** [comment]
This will remain blocked until 444 is completed

**Comment by jamesgreen-moj** [comment]
Looking at the history, now the scaling out metric has been added, we are scaling our ECS clusters successfully.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a5351d6d7a31897fd658190b05b71160cb476f7/image.png)

The graph shows a scale out occurring in the morning due to higher volumes of requests.

Looking at CPU statistics, it does show we spike at 100% during high traffic times, however this minor impact to availability is acceptable due to it being a DNS service.

[Private Zenhub Image (https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae32421a431f8f2b539a78fb0f52d4ad832794f7/image.png)

This will need to be continually reviewed when we start onboarding new clients to ensure we don't see severe service dedication with higher volumes of traffic.
