### ISSUE TITLE
Create VPC module 

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/nvvs-devops#456]
### User Story
We aim to separate the VPC module in our codebase from the community module and transition it into a self-hosted module.
### Value / Purpose

The community module undergoes frequent changes, adding unnecessary complexity with limited benefits. Every time a new version is released, Dependabot detects the changes and refactoring often requires substantial effort. Transitioning to a self-hosted module will enable us to eliminate unnecessary dependencies and streamline the process.

### Definition of Done
- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by tomwells98** [comment]
To discuss at after stand up

**Comment by tomwells98** [comment]
Ticket to be updated with the list of 10 repos in scope and the two out of scope

**Comment by tomwells98** [comment]
To be refined further by devs

**Comment by smjmoj** [comment]
We have the following repos with multiple VPC management with the following versions.

`
PaloAlto-pipelines == source   = "github.com/ministryofjustice/terraform-aws-vpc?ref=v0.1.5"
network-access-control-infrastructure == 2.78.0
nvvs-devops-monitor == 5.1.1
staff-device-dns-dhcp-infrastructure pinned locally to 3.14.0
staff-device-logging-infrastructure == 2.50.0
staff-device-shared-services-infrastructure == 5.1.1
staff-infrastructure-network-services == 5.1.1
`

**Comment by smjmoj** [comment]
Decision is to update each VPC to use the latest starting with the oldest 
staff-device-logging-infrastructure == 2.50.0

then
network-access-control-infrastructure == 2.78.0

then
staff-device-dns-dhcp-infrastructure pinned locally to 3.14.0

then
nvvs-devops-monitor == 5.1.1
staff-device-shared-services-infrastructure == 5.1.1
staff-infrastructure-network-services == 5.1.1

Current [version is 5.4](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/5.4.0)

Then in order to reduce noise configure Dependabot to inform us when the version 6x is released.

**Comment by tomwells98** [comment]
A new path forward to be defined on the next engineers meeting on 18/12/2023.

**Comment by juddin927** [comment]
https://github.com/ministryofjustice/network-access-control-infrastructure/issues/257

**Comment by juddin927** [comment]
https://github.com/ministryofjustice/network-access-control-infrastructure/issues/258  for dependabot

**Comment by juddin927** [comment]
https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/issues/314
