### ISSUE TITLE
Dependabot 08/11/2023

### ISSUE THREAD

**Issue by tomwells98** [ministryofjustice/nvvs-devops#520]
Repo chosen for this sprint:

network-access-control-infrastructure 

The "network-access-control-infrastructure" Terraform repo doesn't have Dependabot configured yet.

The VPC module uses the community module and is currently set at 2.70.0

In the "staff-device-dns-dhcp-infrastructure" we have frozen the module by copying it into the repo, resulting in severing the relationship with the community module.
That has been done because there are no changes to the VPC configuration, so the constant changes in the community module create unnecessary noise and risk.

We planned to follow that same pattern in the network-access-control-infrastructure repo.

**Comment by smjmoj** [comment]
The "network-access-control-infrastructure" Terraform repo doesn't have Dependabot configured yet.

The VPC module uses the community module and is currently set at 2.70.0

In the "staff-device-dns-dhcp-infrastructure" we have frozen the module by copying it into the repo, resulting in severing the relationship with the community module.
That has been done because there are no changes to the VPC configuration, so the constant changes in the community module create unnecessary noise and risk.

We planned to follow that same pattern in the network-access-control-infrastructure repo.

**Comment by smjmoj** [comment]
"The "network-access-control-infrastructure" Terraform repo doesn't have Dependabot configured yet."

After a bit of research and discussion with Aaron we learned that in most Terraform infra repos Renovate Bot has been configured.
During the configuration of this repo to use Renovate we discovered that the Renovate bot had an issue which prevented it completing a run through the configured repos.
Work to resolve that was done, those changes have been linked to this ticket. They were necessary in order to achieve this first goal.
The Renovate bot now works for this repository.
There are at this moment ten pull requests generated by Renovate Bot.

However the decision to use Renovate while valid at the time because Depndabot didn't support Terraform is now outdated.
Suggest we remove the Renovate repository and remove configuration for Renovate managed repositories. For consistency we should only use Dependabot as it's integrated with GitHub and we can use the single view of all Dependabots.
